# Generated by Django 4.2.7 on 2026-02-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6C63FF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('subject', models.CharField(default='General', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('lesson_blocks', models.JSONField(default=list)),
                ('conversation', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('blocks_completed', models.IntegerField(default=0)),
                ('interruptions_count', models.IntegerField(default=0)),
                ('comprehension_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_count', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('last_session', models.DateTimeField(blank=True, null=True)),
                ('mastery_level', models.FloatField(default=0.0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_progress',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
